import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    inventory_stock: 'Inventory & Stock',
    categories: 'Categories',
    menu_premix: 'Menu & Premix',
    wastage_expiry: 'Wastage & Expiry',
    vendors_clients: 'Vendors & Clients',
    purchase_orders: 'Purchase Orders',
    production_distribution: 'Production & Distribution',
    direct_sales: 'Direct Sales (POS)',
    analytics_forecasts: 'Analytics & Forecasts',
    kd_currency: 'د.ك',
    reports_bi: 'Reports & BI',
    accounts: 'Accounts',
    sales_team: 'Sales Team',
    administration: 'Administration',
    settings: 'Settings',
    main: 'Main',
    operations: 'Operations',
    admin: 'Admin',
    search_operations: 'Search operations...',
    logout: 'Logout',
    notifications: 'Notifications',
    clear_all: 'Clear All',
    no_new_alerts: "No new alerts. You're all caught up! ✨",
    powered_by: 'Powered by',
    operations_hub: 'Operations Hub',
    welcome: 'Welcome',
    stock_in: 'Stock In',
    inventory_value: 'Inventory Value',
    active_orders: 'Active Orders',
    daily_revenue: 'Daily Revenue',
    system_waste: 'System Waste',
    real_time: 'Real-time',
    live: 'Live',
    today: 'Today',
    audit: 'Audit',
    low_stock_alerts: 'Low Stock Alerts',
    view_full_inventory: 'View Full Inventory',
    stock_level: 'Stock Level',
    all_stock_healthy: 'All stock levels are healthy!',
    operational_pulse: 'Operational Pulse',
    orders_live: 'Orders Live',
    dispatch_required: 'Dispatch Required',
    dispatch_queue_msg: 'orders are currently in the dispatch queue.',
    no_pending_dispatches: 'No pending dispatches at this moment.',
    high_waste_warning: 'High Waste Warning',
    waste_percentage_msg: 'Wastage is currently',
    of_inventory_value: 'of inventory value.',
    real_time_overview: 'Your real-time operations overview at a glance.',
    total_items: 'Total Items',
    low_stock: 'Low Stock',
    total_value_kd: 'Total Value (د.ك)',
    search_sku_name: 'Search by SKU, Name...',
    filter: 'Filter',
    add_stock_item: 'Add Stock Item',
    item_details: 'Item Details',
    sku: 'SKU',
    category: 'Category',
    current_stock: 'Current Stock',
    min_level: 'Min Level',
    cost_price: 'Cost Price',
    status: 'Status',
    actions: 'Actions',
    loading_stock: 'Loading stock...',
    no_stock_items: 'No stock items found.',
    healthy: 'Healthy',
    adjust_stock: 'Adjust Stock',
    edit_item: 'Edit Item',
    delete: 'Delete',
    are_you_sure: 'Are you sure?',
    revert_msg: "You won't be able to revert this data!",
    yes_delete: 'Yes, delete it!',
    deleted_success: 'Inventory item deleted successfully! 🗑️',
    delete_fail: 'Failed to delete item. It might be linked to existing recipes.',
    menu_recipe_management: 'Menu & Recipe Management',
    selling_items: 'Selling Items',
    kitchen_premixes: 'Kitchen Premixes',
    search_menu_hint: 'Search Menu (e.g. Latte, Coffee...)',
    define_new_premix: 'Define New Premix',
    create_menu_item: 'Create Menu Item',
    product_details: 'Product Details',
    sale_price: 'Sale Price',
    loading_data: 'Loading data...',
    general: 'General',
    view_recipe: 'View Recipe',
    production_log: 'Production Log',
    define_kitchen_premix: 'Define Kitchen Premix',
    configure_menu_item: 'Configure Menu Item & Recipe',
    basic_information: 'Basic Information',
    item_name_en: 'ITEM NAME (ENGLISH)',
    item_name_ar: 'ITEM NAME (ARABIC)',
    category_star: 'CATEGORY *',
    select_category: 'Select Category',
    base_unit: 'BASE UNIT (BATCH)',
    barcode: 'BARCODE',
    scan_barcode_hint: 'Scan or enter barcode',
    selling_price_kd: 'SELLING PRICE (د.ك)',
    total_production_cost: 'TOTAL PRODUCTION COST',
    cost_price_recipe: 'COST PRICE (RECIPE)',
    marketing_descriptions: 'Marketing Descriptions',
    description_en: 'DESCRIPTION (ENGLISH)',
    description_ar: 'DESCRIPTION (ARABIC)',
    recipe_ingredients_bom: 'Recipe Ingredients (BOM)',
    link_ingredient: 'Link Ingredient',
    raw_material_premix: 'RAW MATERIAL / PREMIX',
    search_ingredient_hint: 'Search Ingredient...',
    measurement_unit: 'MEASUREMENT UNIT',
    amount_used: 'AMOUNT USED',
    no_ingredients_linked: 'No ingredients linked yet.',
    cancel: 'Cancel',
    update_kitchen_premix: 'Update Kitchen Premix',
    update_menu_item: 'Update Menu Item',
    create_kitchen_premix: 'Create Kitchen Premix',
    delete_menu_item_q: 'Delete Menu Item?',
    delete_menu_item_msg: 'This will permanently remove this item from your catalog. Are you sure?',
    item_updated: 'Menu Item Updated! ✨',
    item_added: 'New Item Added to Catalog! 🍽️',
    save: 'Save',
    vendors_dist_clients: 'Vendors & Distribution Clients',
    search_partners_hint: 'Search suppliers or clients...',
    add_new_partner: 'Add New Partner',
    partner_name: 'Partner Name',
    contact_details: 'Contact Details',
    type: 'Type',
    default_discount: 'Default Discount',
    partner_updated: 'Partner Updated Successfully! 🤝',
    partner_registered: 'New Partner Registered! 🏢',
    update_partner: 'Update Partner',
    register_partner: 'Register Partner',
    partner_type: 'Partner Type',
    supplier_inbound: 'Supplier (Inbound Goods)',
    client_outbound: 'Distribution Client (Outbound Sales)',
    contact_person: 'Contact Person',
    email_address: 'Email Address',
    phone: 'Phone',
    branches_locations: 'Branches & Delivery Locations',
    add_new_branch: '+ Add New Branch',
    branch_name: 'Branch Name',
    address: 'Address',
    no_branches_msg: 'No branches defined yet. Click \'+ Add New Branch\' to start segregating locations.',
    save_partner_network: 'Save Partner & Network',
    remove_partner_q: 'Remove Partner?',
    remove_partner_msg: 'Are you sure you want to remove this vendor/client?',
    partner_removed: 'Partner removed successfully! 🚮',
    category_management: 'Category Management',
    create_new_category: 'Create New Category',
    category_name: 'Category Name',
    level: 'Level',
    order: 'Order',
    loading_categories: 'Loading categories...',
    primary: 'Primary',
    sub_category: 'Sub-Category',
    edit_category: 'Edit Category',
    parent_category_opt: 'Parent Category (Optional - For Sub-Categories)',
    none_top_level: 'None (Top Level)',
    category_name_en_star: 'Category Name In English *',
    category_name_ar_star: 'Category Name In Arabic *',
    save_category: 'Save Category',
    remove_category_q: 'Remove Category?',
    remove_category_msg: 'This will hide linked menu items. Are you sure?',
    category_removed: 'Category Removed! 🗑️',
    category_updated_success: 'Category Updated Successfully! 📂',
    accounts_finance: 'Accounts & Finance',
    total_revenue: 'Total Revenue',
    total_expenses: 'Total Expenses',
    net_profit: 'Net Profit',
    net_revenue: 'Net Revenue',
    gross_profit: 'Gross Profit',
    estimated_tax: 'Estimated Tax',
    live_tracking: 'Live tracking',
    expenditures: 'Expenditures',
    current_balance: 'Current Balance',
    auto_calculated: 'Auto-calculated',
    fiscal_period: 'Fiscal Period',
    financial_filter: 'Financial Filter',
    export_statements: 'Export Statements',
    record_entry: 'Record Entry',
    transaction_id: 'Transaction ID',
    category_purpose: 'Category / Purpose',
    reference: 'Reference',
    amount_kd: 'Amount (د.ك)',
    syncing_financial_records: 'Syncing financial records...',
    no_financial_records: 'No financial records found.',
    analytics_bi: 'Analytics & Business Intelligence',
    calculating_profits_loss: 'Calculating Profits & Loss Patterns...',
    mfg_health_score: 'Manufacturing Health Score',
    system_efficiency_index: 'System Efficiency Index',
    production_optimized_msg: 'Your production is optimized. Targeting {score}% next week.',
    profit_loss_overview_7d: 'Profit & Loss Overview (7D)',
    total_settled_revenue: 'Total Settled Revenue',
    total_returns_loss: 'Total Returns (Loss)',
    net_profit_after_costs: 'Net Profit (After Costs)',
    expired_wastage_potential: 'Expired Wastage Potential',
    top_revenue_stores_7d: 'Top Revenue Stores (7D Performance)',
    profit_expansion_deck: 'Profit Expansion Deck',
    high_demand_low_waste_msg: 'Stores below have high demand with ZERO waste. Add more quantity here to increase revenue.',
    potential: 'Potential',
    gathering_sales_data: 'System is still gathering sales data to identify expansion targets.',
    leak_growth_forecast: 'Financial Leak & Growth Forecast',
    export_bi_report: 'Export BI Report',
    ai_profit_logic_active: 'AI Profit Logic Active',
    adjustment_recommendation: 'Adjustment Recommendation',
    lost: 'Lost',
    no_loss: '0 Loss',
    no_data_analytical_msg: 'No data available for analytical forecasting yet.',
    earn_everything_back: 'To Earn Everything Back:',
    expand_inventory: 'EXPAND INVENTORY',
    sys_administration: 'System Administration',
    staff_management: 'Staff Management',
    branch_network: 'Branch Network',
    audit_logs: 'Audit Logs',
    search_tab_hint: 'Search {tab}...',
    add_user: 'Add User',
    new_branch: 'New Branch',
    admin_name: 'Admin Name',
    username: 'Username',
    email_contact: 'Email / Contact',
    role: 'Role',
    created: 'Created',
    fetching_staff_records: 'Fetching staff records...',
    no_staff_found: 'No staff found.',
    branch_name_en: 'Branch Name (EN)',
    branch_name_ar: 'Branch Name (AR)',
    syncing_network: 'Syncing network...',
    no_branches_recorded: 'No branches recorded.',
    timestamp: 'Timestamp',
    ip_address: 'IP Address',
    pulling_audit_trail: 'Pulling audit trail...',
    no_logs_found: 'No logs found.',
    register_staff_account: 'Register New Staff Account',
    first_name: 'First Name',
    last_name: 'Last Name',
    secret_password: 'Secret Password',
    system_role: 'System Role',
    choose_role: 'Choose a Role...',
    create_account: 'Create Account',
    add_branch: 'Add Branch',
    staff_account_success: 'Staff Account Registered Successfully! 👤',
    branch_network_success: 'New Branch Network Added! 🏢',
    sales_team_management: 'Sales Team Management',
    active_team: 'Active Team',
    members: 'Members',
    top_performer: 'Top Performer',
    team_revenue: 'Team Revenue',
    search_salesman_hint: 'Search by name or phone...',
    recruit_salesman: 'Recruit Salesman',
    revenue: 'Revenue',
    orders: 'Orders',
    commission: 'Commission',
    monthly_target_progress: 'Monthly Target Progress',
    no_salesmen_found: 'No salesmen found matching your criteria.',
    update_salesman_profile: 'Update Salesman Profile',
    recruit_new_salesman: 'Recruit New Salesman',
    full_name_en_star: 'Full Name (English) *',
    full_name_ar: 'Full Name (Arabic)',
    commission_rate_percent: 'Commission Rate (%)',
    employment_status: 'Employment Status',
    active: 'Active',
    inactive_on_leave: 'Inactive / On Leave',
    confirm_recruitment: 'Confirm Recruitment',
    salesman_updated_success: 'Salesman updated successfully! 👔',
    new_salesman_success: 'New salesman recruited! 🚀',
    remove_salesman_q: 'Are you sure?',
    remove_salesman_msg: 'This salesman will be removed from active duty!',
    wastage_tracking: 'Wastage & Spoilage Tracking',
    todays_loss: "Today's Loss",
    needs_monitoring: 'Needs monitoring',
    total_month_loss: 'Total Month Loss',
    wastage_events: 'Wastage Events',
    primary_reason: 'Primary Reason',
    expired_spoilage: 'Expired (Spoilage)',
    operational_focus: 'Operational focus',
    search_wastage_hint: 'Search by SKU, Product Name...',
    reason_filter: 'Reason Filter',
    report_wastage: 'REPORT WASTAGE',
    product_information: 'Product Information',
    loss_value: 'Loss Value',
    date_recorded: 'Date Recorded',
    reported_by: 'Reported By',
    syncing_wastage_logs: 'Syncing wastage logs...',
    no_wastage_records: 'No wastage records found. Good job!',
    load_more: 'Load More',
    report_product_loss: 'Report Product Loss',
    raw_material_inventory: 'Raw Material (Inventory)',
    finished_product_menu: 'Finished Product (Menu Item)',
    select_damaged_item: 'SELECT DAMAGED ITEM *',
    choose_stock_item: '-- Choose Stock Item --',
    choose_menu_item: '-- Choose Menu Item --',
    quantity_wasted: 'QUANTITY WASTED *',
    select_reason: '-- Select Reason --',
    damaged_dropped: 'Damaged / Dropped',
    kitchen_spill: 'Kitchen Spill',
    defected_batch: 'Defected Batch',
    operational_sample: 'Operational Sample',
    internal_audit_notes: 'INTERNAL AUDIT NOTES',
    provide_audit_details: 'Provide details for management audit...',
    wastage_report_success: 'Wastage Report Submitted! 📉',
    waste_percentage_curr_msg: 'Wastage is currently {val}% of inventory value.',
    dispatch_unit: 'Dispatch',
    production_distribution_hub: 'Production & Distribution Hub',
    client_distribution: 'Client Distribution',
    batch_production: 'Batch Production',
    returns_wastage: 'Returns & Wastage',
    search_orders_batches: 'Search orders or batches...',
    new_production_batch: 'New Production Batch',
    create_dispatch: 'Create Dispatch',
    process_sales_return: 'Process Sales Return',
    internal_distribution: 'Internal Distribution',
    factory_production_history: 'Factory Production History',
    real_time_traceability: 'Real-time Traceability',
    so_number: 'SO #',
    distribution_partner: 'Distribution Partner',
    return_id: 'Return ID',
    wastage_value_loss: 'Wastage Value (Loss)',
    batch_code: 'Batch Code',
    mfd_date: 'Mfd Date',
    exp_date: 'Exp Date',
    line_count: 'Line Count',
    batch_size: 'Batch Size',
    no_distributions_found: 'No distributions found.',
    no_returns_recorded: 'No returns recorded.',
    no_production_found: 'No production logs found.',
    branch: 'Branch',
    deliver: 'Deliver',
    expired_unsold: 'Expired / Unsold',
    preparing_print_doc: 'Preparing document for print...',
    failed_fetch_print_data: 'Failed to fetch print data',
    aggregating_items: 'Aggregating items from selected dispatches...',
    production_batch_success: 'Production Batch Recorded Successfully! 🏭',
    delete_production_q: 'Delete Production Batch?',
    delete_production_msg: 'This action cannot be undone and will NOT restore used stock automatically.',
    production_deleted_success: 'Production batch deleted! 🗑️',
    delete_dispatch_q: 'Delete Dispatch Order?',
    delete_dispatch_msg: 'Are you sure you want to permanently delete this distribution record?',
    dispatch_deleted_success: 'Dispatch order deleted! 🗑️',
    order_marked_delivered: 'Order marked as delivered! ✅',
    return_updated_success: 'Return record updated successfully! ✨',
    return_processed_success: 'Returns Processed & Wastage Recorded! 🔄',
    goods_dispatched_success: 'Goods Dispatched & Linked to Batch! 🚛',
    purchase_management: 'Purchase Management',
    track_procurement_msg: 'Track and manage your procurement operations.',
    create_purchase: 'CREATE PURCHASE',
    final_total: 'Final Total',
    receive_goods_q: 'Receive Goods?',
    receive_goods_msg: 'This will confirm the delivery and INCREMENT your inventory stock!',
    yes_receive_stock: 'Yes, Receive & Stock',
    inventory_updated_success: 'Inventory Updated Successfully! 🚛',
    receive_stock: 'Receive Stock',
    edit_order: 'Edit Order',
    view_order: 'View Order',
    delete_order: 'Delete Order',
    add_new_po: 'ADD NEW PURCHASE ORDER',
    vendor_account: 'Supplier Account',
    select_vendor_account: 'Select Supplier Account',
    target_branch_node: 'Target Branch / Node',
    select_delivery_node: 'Select Delivery Node',
    main_central_node: 'Main / Central Node',
    purchase_date: 'Purchase Date',
    bill_type: 'Bill Type',
    tax_invoice: 'Tax Invoice',
    simplified_bill: 'Simplified Bill',
    order_notes: 'Order Notes',
    internal_notes_hint: 'Internal notes...',
    line_items_list: 'LINE ITEMS LIST',
    products_added: 'Products Added',
    variant: 'VARIANT',
    package: 'PACKAGE',
    price: 'PRICE',
    qty: 'QTY',
    subtotal: 'SUBTOTAL',
    disc: 'DISC.',
    net_final: 'NET FINAL',
    choose_item: 'Choose item...',
    add_new_line_item: 'ADD NEW LINE ITEM',
    internal_communication: 'Internal Communication',
    write_requirements_hint: 'Write any specific requirements or delivery instructions here...',
    subtotal_summary: 'Sub-Total Summary',
    overall_discount: 'Overall Discount',
    grand_total_due: 'Grand Total Due',
    confirm_save: 'CONFIRM & SAVE',
    purchase_order_success: 'Purchase Order Created Successfully! 🧾',
    failed_load_details: 'Failed to load details',
    menu_item_deleted_success: 'Menu Item Deleted Successfully! 🗑️',
    failed_delete_item: 'Failed to delete item',
    operation_failed: 'Operation failed.',
    failed_save_menu_item: 'Failed to save menu item. Please check all required fields.',
    enter_name_en: 'Enter name in English',
    enter_name_ar: 'Enter name in Arabic',
    base_unit_batch: 'Base Unit (for production)',
    piece_unit: 'Piece',
    kg_unit: 'Kilogram (Kg)',
    gram_unit: 'Gram (g)',
    liter_unit: 'Liter (L)',
    ml_unit: 'Milliliter (ml)',
    grams_unit: 'Grams (g)',
    raw_materials: 'Raw Materials',
    sales_dispatch_center: 'Sales & Dispatch Center',
    todays_revenue: "Today's Revenue",
    pending_dispatch: 'Pending Dispatch',
    total_orders: 'Total Orders',
    completed_transfers: 'Completed Transfers',
    search_sales_hint: 'Search by Order ID or Customer Name...',
    all_status: 'All Status',
    new_direct_sale: 'NEW DIRECT SALE',
    order_info: 'Order Info',
    customer: 'Customer',
    payment: 'Payment',
    dispatch_status: 'Dispatch Status',
    items_included: 'items included',
    standard_pdf_print: 'Standard PDF Print',
    dot_matrix_print: 'Dot Matrix Print',
    return_order: 'Return Order',
    order_details: 'Order Details',
    quantity: 'Quantity',
    net_total: 'Net Total',
    record_distribution_sale: 'Record Distribution Sale',
    distribution_partner_caps: 'DISTRIBUTION PARTNER *',
    delivery_branch_node_caps: 'DELIVERY BRANCH NODE *',
    production_batch_caps: 'PRODUCTION BATCH *',
    assign_salesman_caps: 'ASSIGN SALESMAN',
    selection_menu: 'Selection Menu',
    finalize_distribution: 'FINALIZE DISTRIBUTION & RECORD SALE',
    modify_order: 'Modify Order',
    main_corporate_hub: 'Main Corporate Hub',
    choose_client: 'Choose Client...',
    select_destination: 'Select Destination...',
    choose_batch: 'Choose Batch...',
    choose_salesman: 'Choose Salesman...',
    failed_load_order_items: 'Failed to load order items for editing.',
    order_updated_success: 'Order fully updated and stock reconciled!',
    order_status_now: 'Order status is now {val}! 📦',
    payment_status_marked: 'Payment status marked as {val}! 💰',
    invalid_sale_id: 'Invalid Sale ID detected.',
    return_confirm_q: 'Are you sure you want to RETURN Order #{val}? This will RESTORE the ingredient stock to the inventory. 🔄',
    order_returned_success: 'Order {val} has been returned. Stock levels restored! 🔄',
    order_deleted_success: 'Order deleted successfully! 🗑️',
    cart_empty_warning: 'Cart is empty.',
    select_branch_warning: 'Please select a target branch.',
    select_batch_warning: 'Please select a production batch for distribution.',
    sale_recorded_success: 'Sale & Branch Segregation Recorded! 💹',
    discount_percentage_caps: 'DISCOUNT PERCENTAGE (%)',
    current_cart: 'Current Cart',
    remove: 'REMOVE',
    add_more_products: 'Add More Products',
    cancel_changes: 'Cancel Changes',
    save_sync_order: 'SAVE & SYNC ORDER',
    kwd: 'د.ك',
    bi_reports: 'Business Intelligence Reports',
    date_range: 'Date Range',
    to: 'to',
    filter_by_customer: 'Filter by Customer',
    all_customers: 'All Customers',
    filter_by_branch: 'Filter by Branch',
    all_branches: 'All Branches',
    select_customer_first: 'Select Customer First',
    filter_by_salesman: 'Filter by Salesman',
    all_salesmen: 'All Salesmen',
    quick_search: 'Quick Search',
    filter_results_hint: 'Filter results...',
    sales_revenue_tab: 'Sales & Revenue',
    production_logs_tab: 'Production Logs',
    wastage_loss_tab: 'Wastage & Loss',
    purchase_reports_tab: 'Purchase Reports',
    product_performance_tab: 'Product Performance',
    hero_product: 'Hero Product',
    top_selling_hero: 'Top Selling Hero',
    total_qty_sold: 'Total Qty Sold',
    revenue_generated: 'Revenue Generated',
    profit_contribution: 'Profit Contribution',
    item_name: 'Item Name',
    total_sold: 'Total Sold',
    most_profitable: 'Most Profitable',
    all_suppliers: 'All Suppliers',
    po_number: 'PO Number',
    tax: 'Tax',
    print_report: 'Print Report',
    export_csv: 'Export CSV',
    revenue_profit_trend: 'Revenue vs Net Profit Trend',
    top_customers_revenue: 'Top Customers by Revenue',
    wastage_breakdown: 'Wastage Breakdown',
    order_id: 'Order ID',
    total_amt: 'Total Amt',
    final_amt: 'Final Amt',
    qty_produced: 'Qty Produced',
    total_cost: 'Total Cost',
    qty_wasted_caps: 'Qty',
    no_records_period: 'No records found for this period.',
    refreshing_report_data: 'Refreshing Report Data...',
    batch_number_caps: 'Batch Number',
    pending: 'Pending',
    dispatched: 'Dispatched',
    delivered: 'Delivered',
    received: 'Received',
    active_status: 'Active',
    inactive_status: 'Inactive',
    suspended_status: 'Suspended',
    global_configuration: 'Global Configuration',
    manage_system_defaults_msg: 'Manage system-wide defaults and business information.',
    update_settings: 'Update Settings',
    saving: 'Saving...',
    general_tab: 'General',
    production_tab: 'Production',
    financials_tab: 'Financials',
    business_identity: 'Business Identity',
    company_name_label: 'Company Name',
    enter_business_name: 'Enter business name',
    display_address: 'Display Address',
    physical_address_hint: 'Physical address for labels/invoices',
    primary_contact: 'Primary Contact',
    manufacturing_logic: 'Manufacturing Logic',
    default_expiry_buffer_days: 'Default Expiry Buffer (Days)',
    auto_expiry_hint: 'Automatically sets the [Use By] date based on production date.',
    shelf_life_note: "Note: Typical shelf life for products is 4 days including production day.",
    accounting_localization: 'Accounting & Localization',
    service_currency_symbol: 'Service Currency Symbol',
    vat_percentage_label: 'GST/VAT Percentage (%)',
    gathering_configs: 'Gathering system configurations...',
    settings_updated_success: 'System Settings Updated Successfully! ⚙️',
    failed_update_configs: 'Failed to update system configurations.',
    dispatch_dashboard: 'Dispatch Dashboard',
    sales_velocity: 'Sales Velocity (Daily)',
    forecasted_return_rate: 'Forecasted Return Rate',
    optimal_next_dispatch: 'Optimal Next Dispatch',
    expected_savings: 'Expected Cost Savings',
    daily_sales_velocity: 'Daily Sales Run-rate',
    stable: 'Stable',
    reduce_dispatch: 'Reduce Dispatch',
    expand_supply: 'Expand Supply',
    maintain: 'Maintain Supply',
    optimal_dispatch_units: 'Optimal Dispatch Units',
    return_loss_savings: 'Return Loss Savings',
    food_cost: 'Food Cost',
    client_statements: 'Client Statements & Invoices',
    statement_period: 'Statement Period',
    total_sent: 'Total Sent',
    paid_amount: 'Paid Amount',
    balance_due: 'Balance Due',
    no_statements: 'No client statements found for the selected range.',
    print_statement: 'Print Statement',
    payment_status_filter: 'Payment Status',
    opening_stock: 'Opening Stock',
    receiving: 'Receiving Stock',
    transfers_in: 'Transfer In',
    transfers_out: 'Transfer Out',
    wastage_title: 'Wastage (Expired)',
    closing_stock: 'Closing Stock (EOM)',
    food_cost_report: 'Food Cost Report',
    food_cost_percentage: 'Food Cost % of Sales',
    profit_loss_report: 'Profit & Loss Report',
    formula_desc: 'Calculation: Opening Stock + Receiving Stock + Transfer In - Transfer Out + Wastage - Closing Stock = Food Cost'
  },
  ar: {
    dashboard: 'لوحة القيادة',
    inventory_stock: 'المخزون والسلع',
    categories: 'التصنيفات',
    menu_premix: 'القائمة والخلطات',
    wastage_expiry: 'الهدر والصلاحية',
    vendors_clients: 'الموردين والعملاء',
    purchase_orders: 'أوامر الشراء',
    production_distribution: 'الإنتاج والتوزيع',
    direct_sales: 'المبيعات المباشرة',
    analytics_forecasts: 'التحليلات والتوقعات',
    reports_bi: 'التقارير وذكاء الأعمال',
    accounts: 'الحسابات',
    sales_team: 'فريق المبيعات',
    administration: 'الإدارة',
    settings: 'الإعدادات',
    main: 'الرئيسية',
    operations: 'العمليات',
    admin: 'الإدارة',
    search_operations: 'البحث في العمليات...',
    logout: 'تسجيل الخروج',
    notifications: 'الإشعارات',
    clear_all: 'مسح الكل',
    no_new_alerts: 'لا توجد تنبيهات جديدة. أنت على اطلاع دائم! ✨',
    powered_by: 'مشغل بواسطة',
    operations_hub: 'مركز العمليات',
    welcome: 'مرحباً',
    stock_in: 'إضافة مخزون',
    inventory_value: 'قيمة المخزون',
    active_orders: 'الطلبات النشطة',
    daily_revenue: 'الإيرادات اليومية',
    system_waste: 'هدر النظام',
    real_time: 'في الوقت الحقيقي',
    live: 'مباشر',
    today: 'اليوم',
    audit: 'تدقيق',
    low_stock_alerts: 'تنبيهات انخفاض المخزون',
    view_full_inventory: 'عرض المخزون بالكامل',
    stock_level: 'مستوى المخزون',
    all_stock_healthy: 'جميع مستويات المخزون سليمة!',
    operational_pulse: 'نبض العمليات',
    orders_live: 'طلبات مباشرة',
    dispatch_required: 'مطلوب التوزيع',
    dispatch_queue_msg: 'طلبات موجودة حالياً في قائمة التوزيع.',
    no_pending_dispatches: 'لا توجد توزيعات معلقة في الوقت الحالي.',
    high_waste_warning: 'تحذير من ارتفاع الهدر',
    waste_percentage_msg: 'الهدر حالياً هو',
    of_inventory_value: 'من قيمة المخزون.',
    real_time_overview: 'نظرة عامة على عملياتك في الوقت الفعلي لمحمة سريعة.',
    total_items: 'إجمالي العناصر',
    low_stock: 'انخفاض المخزون',
    total_value_kd: 'إجمالي القيمة (د.ك)',
    search_sku_name: 'البحث بواسطة SKU، الاسم...',
    filter: 'تصفية',
    add_stock_item: 'إضافة عنصر مخزون',
    item_details: 'تفاصيل العنصر',
    sku: 'SKU',
    category: 'الفئة',
    current_stock: 'المخزون الحالي',
    min_level: 'الحد الأدنى',
    cost_price: 'سعر التكلفة',
    status: 'الحالة',
    actions: 'الإجراءات',
    loading_stock: 'جاري تحميل المخزون...',
    no_stock_items: 'لم يتم العثور على عناصر مخزون.',
    healthy: 'سليم',
    adjust_stock: 'تعديل المخزون',
    edit_item: 'تعديل العنصر',
    delete: 'حذف',
    are_you_sure: 'هل أنت متأكد؟',
    revert_msg: "لن تتمكن من التراجع عن هذه البيانات!",
    yes_delete: 'نعم، احذفه!',
    deleted_success: 'تم حذف عنصر المخزون بنجاح! 🗑️',
    delete_fail: 'فشل حذف العنصر. قد يكون مرتبطاً بوصفات موجودة.',
    menu_recipe_management: 'إدارة القائمة والوصفات',
    selling_items: 'أصناف البيع',
    kitchen_premixes: 'خلطات المطبخ',
    search_menu_hint: 'البحث في القائمة (مثلاً: لاتيه، قهوة...)',
    define_new_premix: 'تعريف خلطة جديدة',
    create_menu_item: 'إنشاء صنف جديد',
    product_details: 'تفاصيل المنتج',
    sale_price: 'سعر البيع',
    loading_data: 'جاري تحميل البيانات...',
    general: 'عام',
    view_recipe: 'عرض الوصفة',
    production_log: 'سجل الإنتاج',
    define_kitchen_premix: 'تعريف خلطة مطبخ',
    configure_menu_item: 'تهيئة الصنف والوصفة',
    basic_information: 'المعلومات الأساسية',
    item_name_en: 'اسم الصنف (إنجليزي)',
    item_name_ar: 'الاسم باللغة العربية',
    category_star: 'الفئة *',
    select_category: 'اختر الفئة',
    base_unit: 'الوحدة الأساسية',
    barcode: 'الباركود',
    scan_barcode_hint: 'امسح أو أدخل الباركود',
    selling_price_kd: 'سعر البيع (د.ك)',
    total_production_cost: 'إجمالي تكلفة الإنتاج',
    cost_price_recipe: 'سعر التكلفة (الوصفة)',
    marketing_descriptions: 'أوصاف تسويقية',
    description_en: 'الوصف (إنجليزي)',
    description_ar: 'وصف الصنف بالعربية',
    recipe_ingredients_bom: 'مكونات الوصفة',
    link_ingredient: 'ربط مكون',
    raw_material_premix: 'مادة خام / خلطة',
    search_ingredient_hint: 'البحث عن مكون...',
    measurement_unit: 'وحدة القياس',
    amount_used: 'الكمية المستخدمة',
    no_ingredients_linked: 'لا توجد مكونات مرتبطة بعد.',
    cancel: 'إلغاء',
    update_kitchen_premix: 'تحديث خلطة المطبخ',
    update_menu_item: 'تحديث الصنف',
    create_kitchen_premix: 'إنشاء خلطة مطبخ',
    delete_menu_item_q: 'حذف الصنف؟',
    delete_menu_item_msg: 'سيؤدي هذا إلى إزالة هذا الصنف بشكل دائم من القائمة. هل أنت متأكد؟',
    item_updated: 'تم تحديث الصنف! ✨',
    item_added: 'تم إضافة صنف جديد للقائمة! 🍽️',
    save: 'حفظ',
    vendors_dist_clients: 'الموردين وعملاء التوزيع',
    search_partners_hint: 'البحث عن الموردين أو العملاء...',
    add_new_partner: 'إضافة شريك جديد',
    partner_name: 'اسم الشريك',
    contact_details: 'تفاصيل الاتصال',
    type: 'النوع',
    default_discount: 'الخصم الافتراضي',
    partner_updated: 'تم تحديث الشريك بنجاح! 🤝',
    partner_registered: 'تم تسجيل شريك جديد! 🏢',
    update_partner: 'تحديث الشريك',
    register_partner: 'تسجيل شريك',
    partner_type: 'نوع الشريك',
    supplier_inbound: 'مورد (بضائع واردة)',
    client_outbound: 'عميل توزيع (مبيعات صادرة)',
    contact_person: 'الشخص المسؤول',
    email_address: 'البريد الإلكتروني',
    phone: 'الهاتف',
    branches_locations: 'الفروع ومواقع التسليم',
    add_new_branch: '+ إضافة فرع جديد',
    branch_name: 'اسم الفرع',
    address: 'العنوان',
    no_branches_msg: 'لم يتم تعريف أي فروع بعد. انقر فوق "+ إضافة فرع جديد" لبدء فصل المواقع.',
    save_partner_network: 'حفظ الشريك والشبكة',
    remove_partner_q: 'حذف الشريك؟',
    remove_partner_msg: 'هل أنت متأكد أنك تريد حذف هذا المورد/العميل؟',
    partner_removed: 'تم حذف الشريك بنجاح! 🚮',
    category_management: 'إدارة التصنيفات',
    create_new_category: 'إنشاء تصنيف جديد',
    category_name: 'اسم التصنيف',
    level: 'المستوى',
    order: 'الترتيب',
    loading_categories: 'جاري تحميل التصنيفات...',
    primary: 'أساسي',
    sub_category: 'تصنيف فرعي',
    edit_category: 'تعديل التصنيف',
    parent_category_opt: 'التصنيف الأب (اختياري - للتصنيفات الفرعية)',
    none_top_level: 'لا يوجد (المستوى الأعلى)',
    category_name_en_star: 'اسم التصنيف بالإنجليزي *',
    category_name_ar_star: 'اسم التصنيف بالعربي *',
    save_category: 'حفظ التصنيف',
    remove_category_q: 'حذف التصنيف؟',
    remove_category_msg: 'سيؤدي هذا إلى إخفاء أصناف القائمة المرتبطة. هل أنت متأكد؟',
    category_removed: 'تم حذف التصنيف! 🗑️',
    category_updated_success: 'تم تحديث التصنيف بنجاح! 📂',
    accounts_finance: 'الحسابات والمالية',
    total_revenue: 'إجمالي الإيرادات',
    total_expenses: 'إجمالي المصاريف',
    net_profit: 'صافي الربح',
    net_revenue: 'صافي الإيرادات',
    gross_profit: 'إجمالي الربح',
    estimated_tax: 'الضريبة المقدرة',
    live_tracking: 'تتبع مباشر',
    expenditures: 'المصروفات',
    current_balance: 'الرصيد الحالي',
    auto_calculated: 'محسوب تلقائياً',
    fiscal_period: 'الفترة المالية',
    financial_filter: 'تصفية مالية',
    export_statements: 'تصدير الكشوفات',
    record_entry: 'تسجيل قيد',
    transaction_id: 'رقم المعاملة',
    category_purpose: 'الفئة / الغرض',
    reference: 'المرجع',
    amount_kd: 'المبلغ (د.ك)',
    syncing_financial_records: 'جاري مزامنة السجلات المالية...',
    no_financial_records: 'لم يتم العثور على سجلات مالية.',
    analytics_bi: 'التحليلات وذكاء الأعمال',
    calculating_profits_loss: 'جاري حساب أنماط الأرباح والخسائر...',
    mfg_health_score: 'درجة صحة التصنيع',
    system_efficiency_index: 'مؤشر كفاءة النظام',
    production_optimized_msg: 'إنتاجك محسن. نستهدف {score}٪ الأسبوع القادم.',
    profit_loss_overview_7d: 'نظرة عامة على الأرباح والخسائر (7 أيام)',
    total_settled_revenue: 'إجمالي الإيرادات المحصلة',
    total_returns_loss: 'إجمالي المرتجعات (خسارة)',
    net_profit_after_costs: 'صافي الربح (بعد التكاليف)',
    expired_wastage_potential: 'إمكانيات الهدر منتهي الصلاحية',
    top_revenue_stores_7d: 'أفضل المتاجر من حيث الإيرادات (أداء 7 أيام)',
    profit_expansion_deck: 'مجموعة توسيع الأرباح',
    high_demand_low_waste_msg: 'المتاجر أدناه لديها طلب مرتفع مع صفر هدر. أضف كمية أكبر هنا لزيادة الإيرادات.',
    potential: 'إمكانيات',
    gathering_sales_data: 'لا يزال النظام يجمع بيانات المبيعات لتحديد أهداف التوسع.',
    leak_growth_forecast: 'توقعات التسريب المالي والنمو',
    export_bi_report: 'تصدير تقرير ذكاء الأعمال',
    ai_profit_logic_active: 'منطق أرباح الذكاء الاصطناعي نشط',
    adjustment_recommendation: 'توصية التعديل',
    lost: 'خسارة',
    no_loss: '0 خسارة',
    no_data_analytical_msg: 'لا تتوفر بيانات للتوقعات التحليلية بعد.',
    earn_everything_back: 'لاستعادة كل شيء:',
    stop_the_leak: 'أوقف التسريب:',
    expand_inventory: 'توسيع المخزون',
    sys_administration: 'إدارة النظام',
    staff_management: 'إدارة الموظفين',
    branch_network: 'شبكة الفروع',
    audit_logs: 'سجلات التدقيق',
    search_tab_hint: 'البحث في {tab}...',
    add_user: 'إضافة مستخدم',
    new_branch: 'فرع جديد',
    admin_name: 'اسم المدير',
    username: 'اسم المستخدم',
    email_contact: 'البريد الإلكتروني / الاتصال',
    role: 'الدور',
    created: 'تم الإنشاء',
    fetching_staff_records: 'جاري جلب سجلات الموظفين...',
    no_staff_found: 'لم يتم العثور على موظفين.',
    branch_name_en: 'اسم الفرع (EN)',
    branch_name_ar: 'اسم الفرع (AR)',
    syncing_network: 'جاري مزامنة الشبكة...',
    no_branches_recorded: 'لا توجد فروع مسجلة.',
    timestamp: 'الطابع الزمني',
    ip_address: 'عنوان IP',
    pulling_audit_trail: 'جاري جلب سجلات التدقيق...',
    no_logs_found: 'لم يتم العثور على سجلات.',
    register_staff_account: 'تسجيل حساب موظف جديد',
    first_name: 'الاسم الأول',
    last_name: 'اسم العائلة',
    secret_password: 'كلمة المرور السرية',
    system_role: 'دور النظام',
    choose_role: 'اختر دوراً...',
    create_account: 'إنشاء حساب',
    add_branch: 'إضافة فرع',
    sale_recorded_success: 'تم تسجيل البيع وتوزيع الفروع! 💹',
    discount_percentage_caps: 'نسبة الخصم (%)',
    current_cart: 'السلة الحالية',
    remove: 'إزالة',
    add_more_products: 'إضافة المزيد من المنتجات',
    cancel_changes: 'إلغاء التغييرات',
    save_sync_order: 'حفظ ومزامنة الطلب',
    kwd: 'د.ك',
    kd_currency: 'د.ك',
    bi_reports: 'تقارير ذكاء الأعمال',
    date_range: 'النطاق الزمني',
    to: 'إلى',
    filter_by_customer: 'تصفية حسب العميل',
    all_customers: 'جميع العملاء',
    filter_by_branch: 'تصفية حسب الفرع',
    all_branches: 'جميع الفروع',
    select_customer_first: 'اختر العميل أولاً',
    filter_by_salesman: 'تصفية حسب مندوب المبيعات',
    all_salesmen: 'جميع المندوبين',
    quick_search: 'بحث سريع',
    filter_results_hint: 'تصفية النتائج...',
    sales_revenue_tab: 'المبيعات والإيرادات',
    production_logs_tab: 'سجلات الإنتاج',
    wastage_loss_tab: 'الهدر والخسارة',
    purchase_reports_tab: 'تقارير المشتريات',
    all_suppliers: 'جميع الموردين',
    po_number: 'رقم طلب الشراء',
    tax: 'الضريبة',
    disc: 'الخصم',
    print_report: 'طباعة التقرير',
    export_csv: 'تصدير CSV',
    revenue_profit_trend: 'اتجاه الإيرادات مقابل صافي الربح',
    top_customers_revenue: 'أفضل العملاء حسب الإيرادات',
    wastage_breakdown: 'توزيع الهدر',
    order_id: 'رقم الطلب',
    total_amt: 'إجمالي المبلغ',
    final_amt: 'المبلغ النهائي',
    qty_produced: 'الكمية المنتجة',
    total_cost: 'إجمالي التكلفة',
    qty_wasted_caps: 'الكمية',
    no_records_period: 'لا توجد سجلات لهذه الفترة.',
    refreshing_report_data: 'جاري تحديث بيانات التقرير...',
    batch_number_caps: 'رقم الدفعة',
    pending: 'قيد الانتظار',
    dispatched: 'تم الإرسال',
    delivered: 'تم التوصيل',
    received: 'تم الاستلام',
    active_status: 'نشط',
    inactive_status: 'غير نشط',
    suspended_status: 'موقوف',
    staff_account_success: 'تم تسجيل حساب الموظف بنجاح! 👤',
    branch_network_success: 'تم إضافة شبكة فروع جديدة! 🏢',
    sales_team_management: 'إدارة فريق المبيعات',
    active_team: 'الفريق النشط',
    members: 'أعضاء',
    top_performer: 'الأفضل أداءً',
    team_revenue: 'إيرادات الفريق',
    search_salesman_hint: 'البحث بالاسم أو الهاتف...',
    recruit_salesman: 'توظيف مندوب مبيعات',
    revenue: 'الإيرادات',
    orders: 'الطلبات',
    commission: 'العمولة',
    monthly_target_progress: 'التقدم في الهدف الشهري',
    no_salesmen_found: 'لم يتم العثور على مناديب مبيعات تطابق معاييرك.',
    update_salesman_profile: 'تحديث ملف المندوب',
    recruit_new_salesman: 'توظيف مندوب مبيعات جديد',
    full_name_en_star: 'الاسم الكامل (إنجليزي) *',
    full_name_ar: 'الاسم بالكامل (عربي)',
    commission_rate_percent: 'نسبة العمولة (%)',
    employment_status: 'حالة التوظيف',
    active: 'نشط',
    inactive_on_leave: 'غير نشط / في إجازة',
    confirm_recruitment: 'تأكيد التوظيف',
    salesman_updated_success: 'تم تحديث بيانات المندوب بنجاح! 👔',
    new_salesman_success: 'تم توظيف مندوب مبيعات جديد! 🚀',
    remove_salesman_q: 'هل أنت متأكد؟',
    remove_salesman_msg: 'سيتم إزالة هذا المندوب من الخدمة الفعلية!',
    wastage_tracking: 'تتبع الهدر والفساد',
    todays_loss: 'خسارة اليوم',
    needs_monitoring: 'يحتاج للمراقبة',
    total_month_loss: 'إجمالي خسارة الشهر',
    wastage_events: 'حالات الهدر',
    primary_reason: 'السبب الرئيسي',
    expired_spoilage: 'منتهي الصلاحية (فساد)',
    operational_focus: 'تركيز عملياتي',
    search_wastage_hint: 'البحث بواسطة SKU، اسم المنتج...',
    reason_filter: 'تصفية حسب السبب',
    report_wastage: 'الإبلاغ عن الهدر',
    product_information: 'معلومات المنتج',
    loss_value: 'قيمة الخسارة',
    date_recorded: 'تاريخ التسجيل',
    reported_by: 'تم الإبلاغ بواسطة',
    syncing_wastage_logs: 'جاري مزامنة سجلات الهدر...',
    no_wastage_records: 'لم يتم العثور على سجلات هدر. عمل جيد!',
    load_more: 'تحميل المزيد',
    report_product_loss: 'الإبلاغ عن خسارة المنتج',
    raw_material_inventory: 'مادة خام (المخزون)',
    finished_product_menu: 'منتج نهائي (صنف القائمة)',
    select_damaged_item: 'اختر العنصر التالف *',
    choose_stock_item: '-- اختر عنصر المخزون --',
    choose_menu_item: '-- اختر صنف القائمة --',
    quantity_wasted: 'الكمية المهدرة *',
    select_reason: '-- اختر السبب --',
    damaged_dropped: 'تالف / سقط',
    kitchen_spill: 'انسكاب في المطبخ',
    defected_batch: 'دفعة معيبة',
    operational_sample: 'عينة عملياتية',
    internal_audit_notes: 'ملاحظات التدقيق الداخلي',
    provide_audit_details: 'قدم تفاصيل لتدقيق الإدارة...',
    record_waste_transfer: 'تسجيل انتقال الهدر',

    global_configuration: 'التكوين العام',
    manage_system_defaults_msg: 'إدارة الإعدادات الافتراضية للنظام ومعلومات العمل.',
    update_settings: 'تحديث الإعدادات',
    saving: 'جاري الحفظ...',
    general_tab: 'عام',
    production_tab: 'الإنتاج',
    financials_tab: 'المالية',
    business_identity: 'هوية العمل',
    company_name_label: 'اسم الشركة',
    enter_business_name: 'أدخل اسم العمل',
    display_address: 'عنوان العرض',
    physical_address_hint: 'العنوان الفعلي للملصقات/الفواتير',
    primary_contact: 'جهة الاتصال الرئيسية',
    manufacturing_logic: 'منطق التصنيع',
    default_expiry_buffer_days: 'مدة الصلاحية الافتراضية (أيام)',
    auto_expiry_hint: 'يضبط تاريخ [يستخدم قبل] تلقائياً بناءً على تاريخ الإنتاج.',
    shelf_life_note: 'ملاحظة: مدة الصلاحية المعتادة للمنتجات هي 4 أيام بما في ذلك يوم الإنتاج.',
    accounting_localization: 'المحاسبة والتعريب',
    service_currency_symbol: 'رمز عملة الخدمة',
    vat_percentage_label: 'نسبة ضريبة القيمة المضافة (%)',
    gathering_configs: 'جاري جمع تكوينات النظام...',
    settings_updated_success: 'تم تحديث إعدادات النظام بنجاح! ⚙️',
    failed_update_configs: 'فشل تحديث تكوينات النظام.',
    purchase_management: 'إدارة المشتريات',
    track_procurement_msg: 'تتبع وإدارة عمليات الشراء الخاصة بك.',
    create_purchase: 'إنشاء شراء',
    final_total: 'الإجمالي النهائي',
    receive_goods_q: 'استلام البضائع؟',
    receive_goods_msg: 'سيؤدي هذا إلى تأكيد التسليم وزيادة مخزون المستودع الخاص بك!',
    yes_receive_stock: 'نعم، استلام وتخزين',
    inventory_updated_success: 'تم تحديث المخزون بنجاح! 🚛',
    receive_stock: 'استلام المخزون',
    edit_order: 'تعديل الطلب',
    view_order: 'عرض الطلب',
    delete_order: 'حذف الطلب',
    add_new_po: 'إضافة أمر شراء جديد',
    vendor_account: 'حساب المورد',
    select_vendor_account: 'اختر حساب المورد',
    target_branch_node: 'الفرع / النقطة المستهدفة',
    select_delivery_node: 'اختر نقطة التسليم',
    main_central_node: 'الفرع الرئيسي / المركز',
    purchase_date: 'تاريخ الشراء',
    bill_type: 'نوع الفاتورة',
    tax_invoice: 'فاتورة ضريبية',
    simplified_bill: 'فاتورة مبسطة',
    order_notes: 'ملاحظات الطلب',
    internal_notes_hint: 'ملاحظات داخلية...',
    line_items_list: 'قائمة الأصناف',
    products_added: 'أصناف مضافة',
    variant: 'النوع',
    package: 'العبوة',
    price: 'السعر',
    qty: 'الكمية',
    subtotal: 'الإجمالي الفرعي',
    net_final: 'الصافي النهائي',
    choose_item: 'اختر صنف...',
    add_new_line_item: 'إضافة صنف جديد',
    internal_communication: 'التواصل الداخلي',
    write_requirements_hint: 'اكتب أي متطلبات محددة أو تعليمات التسليم هنا...',
    subtotal_summary: 'ملخص الإجمالي الفرعي',
    overall_discount: 'الخصم الإجمالي',
    grand_total_due: 'الإجمالي المستحق',
    confirm_save: 'تأكيد وحفظ',
    purchase_order_success: 'تم إنشاء أمر الشراء بنجاح! 🧾',
    product_performance_tab: 'أداء المنتجات',
    hero_product: 'المنتج الأفضل',
    top_selling_hero: 'البطل الأكثر مبيعاً',
    total_qty_sold: 'إجمالي الكمية المباعة',
    revenue_generated: 'الإيرادات المحققة',
    profit_contribution: 'المساهمة في الربح',
    item_name: 'اسم الصنف',
    total_sold: 'إجمالي المباع',
    most_profitable: 'الأكثر ربحية',
    dispatch_unit: 'وحدة',
    dispatch_dashboard: 'لوحة تحكم التوزيع',
    sales_velocity: 'سرعة المبيعات (يومياً)',
    forecasted_return_rate: 'معدل المرتجعات المتوقع',
    optimal_next_dispatch: 'التوزيع المثالي القادم',
    expected_savings: 'الوفورات المتوقعة',
    daily_sales_velocity: 'معدل المبيعات اليومي',
    stable: 'مستقر',
    reduce_dispatch: 'تقليل التوزيع',
    expand_supply: 'توسيع التوريد',
    maintain: 'الحفاظ على التوريد',
    optimal_dispatch_units: 'وحدات التوزيع المثالية',
    return_loss_savings: 'وفورات خسارة المرتجعات',
    food_cost: 'تكلفة الأغذية',
    client_statements: 'كشوفات وفواتير العملاء',
    statement_period: 'فترة الكشف',
    total_sent: 'إجمالي المرسل',
    paid_amount: 'المبلغ المدفوع',
    balance_due: 'الرصيد المستحق',
    no_statements: 'لم يتم العثور على كشوفات للعميل في الفترة المحددة.',
    print_statement: 'طباعة الكشف',
    payment_status_filter: 'حالة الدفع',
    opening_stock: 'مخزون أول المدة',
    receiving: 'مخزون مستلم',
    transfers_in: 'تحويل وارد',
    transfers_out: 'تحويل صادر',
    wastage_title: 'تالف (منتهي الصلاحية)',
    closing_stock: 'مخزون آخر المدة',
    food_cost_report: 'تقرير تكلفة الأغذية',
    food_cost_percentage: 'نسبة تكلفة الأغذية من المبيعات',
    profit_loss_report: 'تقرير الأرباح والخسائر',
    formula_desc: 'المعادلة: مخزون أول المدة + مخزون مستلم + تحويل وارد - تحويل صادر + التالف - مخزون آخر المدة = تكلفة الأغذية'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('lang') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('lang', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
